// Catálogo da demo AI Journey. As 5 soluções liberadas são as pastas deste repositório; cada uma é publicada
// como imagem em ghcr.io/startse/<id> e num branch deploy-<id> de StartSe/ai-action-app-deploy (ver scripts/gerar-deploy.mjs).
// As demais vêm do catálogo do AI Action e aparecem bloqueadas, abrindo o convite para ingressar.
window.AI_JOURNEY = {
  repoDeploy: "https://github.com/StartSe/ai-action-app-deploy",
  ingressarUrl: "https://pages.startse.com/ai-action",
  cupom: "JOURNEY2ACTION",
  checkoutUrl: "https://checkout.startse.com/ai-action-ed1a26?cupom=JOURNEY2ACTION",
  totalCatalogo: 100,
  // Solução por onde "Começar agora" leva quem ainda não implantou nenhuma.
  inicio: "planilha-inteligente-ai-journey",

  liberadas: [
    {
      id: "busca-inteligente-ai-journey",
      nome: "Busca Inteligente",
      demo: true, // só demonstração: a integração completa fica no AI Action
      categoria: "Comercial",
      minutos: 5,
      resumo: "Compara, lado a lado, a busca comum por palavra-chave com uma busca que entende a intenção da frase e dá nota para cada produto da loja.",
      problema: "O cliente escreve \"presente pra minha mãe que ama jardinagem até 150 reais\" e a busca da loja procura só as palavras. Volta pouco, volta errado ou não volta nada, e a venda se perde.",
      quemSofre: "Quem cuida de e-commerce, catálogo ou atendimento e vê o cliente desistir porque não achou o produto que a loja tinha.",
      resultado: "Uma loja de exemplo com 120 produtos em que o Jev lê a intenção, o orçamento e para quem é o presente, com as duas listas lado a lado e o raio-x de cada decisão.",
      processo: "Publicar no Render → criar a conta no app → rodar as buscas de exemplo → conectar o OpenRouter e buscar ao vivo.",
      setup: "/setup",
      servico: "busca-inteligente-ai-journey",
      criterios: [
        ["A aplicação está no ar na sua conta do Render", "Abra a URL que o Render entregou; a tela de criar a conta deve carregar sem erro."],
        ["As buscas de exemplo mostram as duas listas lado a lado", "Clique numa das 8 buscas de exemplo e confira a busca comum de um lado e a busca com o Jev do outro."],
        ["O Jev responde ao vivo com a sua conta do OpenRouter", "Em Configurações, conecte o OpenRouter e escreva uma frase sua; o selo de modo demonstração some e o custo da busca aparece."],
      ],
      roteiro: [
        ["Publicar no Render", "O Render lê o Blueprint e sobe a imagem pronta na sua conta, no plano gratuito. Você não constrói nada.", "Render", 2],
        ["Criar a sua conta no app", "O primeiro acesso cria a conta de administrador. Ela protege a chave da IA que você vai conectar.", "Render", 1],
        ["Testar com as buscas de exemplo", "Sem nenhuma chave, as 8 buscas de exemplo rodam em modo demonstração para você ver a diferença.", "Render", 1],
        ["Conectar o OpenRouter", "Em Configurações, um clique em Conectar com OpenRouter. A partir daí, qualquer frase é avaliada ao vivo.", "OpenRouter", 1],
      ],
      antes: [
        "Uma conta no Render (o plano gratuito serve para esta demo)",
        "Uma conta no OpenRouter com algum crédito, só para buscar ao vivo (cada busca custa cerca de US$ 0,001)",
        "No plano gratuito o app adormece sem uso e a conta se perde a cada nova publicação",
      ],
    },
    {
      id: "estudio-inteligente-ai-journey",
      nome: "Estúdio Inteligente",
      categoria: "Marketing",
      minutos: 5,
      resumo: "Fale do seu negócio e veja site, identidade visual, carrosséis, e-mail marketing e anúncios nascerem juntos, mudando enquanto você fala.",
      problema: "Tirar uma marca do papel exige briefing, agência, designer e várias rodadas de ajuste antes de existir um site, um logo ou um post para testar a ideia.",
      quemSofre: "Quem empreende, lança produto ou cuida de marketing e precisa ver a ideia de pé hoje, sem esperar semanas por peças.",
      resultado: "Site em HTML, logo em SVG, paleta e fontes, 3 carrosséis, e-mail e kit de banners, com as 46 decisões criativas do Jev explicadas no raio-x.",
      processo: "Publicar no Render → criar a conta no app → contar sobre o negócio pela voz ou por texto → ajustar as peças por comando.",
      setup: "/configuracoes",
      servico: "estudio-inteligente-ai-journey",
      criterios: [
        ["A aplicação está no ar na sua conta do Render", "Abra a URL que o Render entregou; a tela de criar a conta deve carregar sem erro."],
        ["Uma fala de exemplo gera todas as peças", "Rode uma fala simulada e confira site, logo, carrosséis, e-mail e anúncios aparecendo juntos."],
        ["As peças respondem a um comando seu", "Peça \"muda o logo pra ficar tipo selo\" e confira que só aquela peça muda e fica travada."],
      ],
      roteiro: [
        ["Publicar no Render", "O Render lê o Blueprint e sobe a imagem pronta na sua conta, no plano gratuito. Você não constrói nada.", "Render", 2],
        ["Criar a sua conta no app", "O primeiro acesso cria a conta de administrador e grava 8 projetos de exemplo.", "Render", 1],
        ["Contar sobre o seu negócio", "Pelo microfone, por uma fala simulada ou digitando. Sem chave, o estúdio roda em modo demonstração.", "Render", 1],
        ["Conectar o OpenRouter", "Em Configurações, Conectar em um clique. O Jev passa a decidir as 46 escolhas criativas ao vivo.", "OpenRouter", 1],
      ],
      antes: [
        "Uma conta no Render (o plano gratuito serve para esta demo)",
        "Chrome, Edge ou Safari para usar o microfone",
        "Uma conta no OpenRouter só para as decisões ao vivo; sem ela, o modo demonstração mostra tudo",
      ],
    },
    {
      id: "planilha-inteligente-ai-journey",
      nome: "Planilha Inteligente",
      categoria: "Operações",
      minutos: 5,
      resumo: "Crie uma coluna escrevendo só o título, como \"É decisor?\" ou \"Urgência\", e veja a planilha inteira preenchida em menos de um segundo.",
      problema: "Planilhas de texto livre, como mensagens de WhatsApp, avaliações e chamados, obrigam alguém a ler linha por linha para responder quem quer comprar, quem decide e qual é o tema.",
      quemSofre: "Quem recebe leads, feedbacks ou chamados em volume e perde horas classificando à mão antes de conseguir agir.",
      resultado: "Uma planilha em que cada coluna nova é uma pergunta ao Jev, com a probabilidade de cada célula, filtro, exportação em CSV e importação de Excel.",
      processo: "Publicar no Render → criar a conta no app → preencher as colunas sugeridas → importar a sua planilha.",
      setup: "/setup",
      servico: "planilha-inteligente-ai-journey",
      criterios: [
        ["A aplicação está no ar na sua conta do Render", "Abra a URL que o Render entregou; a tela de criar a conta deve carregar sem erro."],
        ["A planilha de exemplo é preenchida por uma coluna nova", "Abra Leads do WhatsApp e clique em Preencher «Quer comprar?»; a coluna enche com a % de cada linha."],
        ["A sua planilha entra e é classificada", "Importe um Excel ou CSV seu e crie uma coluna com um título de sua escolha."],
      ],
      roteiro: [
        ["Publicar no Render", "O Render lê o Blueprint e sobe a imagem pronta na sua conta, no plano gratuito. Você não constrói nada.", "Render", 2],
        ["Criar a sua conta no app", "O primeiro acesso cria a conta de administrador e abre a planilha Leads do WhatsApp.", "Render", 1],
        ["Preencher as colunas sugeridas", "Quer comprar?, É decisor? e Porte da empresa, em modo demonstração enquanto não há chave.", "Render", 1],
        ["Conectar o OpenRouter", "Em Configurações, Conectar com o OpenRouter. Cada coluna passa a ser decidida pelo Jev ao vivo.", "OpenRouter", 1],
      ],
      antes: [
        "Uma conta no Render (o plano gratuito serve para esta demo)",
        "Uma planilha sua em Excel (.xlsx), CSV ou JSON, com até 300 linhas e 12 colunas",
        "No plano gratuito, conta e planilhas somem a cada nova publicação ou reinício",
      ],
    },
    {
      id: "site-inteligente-ai-journey",
      nome: "Site Inteligente",
      demo: true, // só demonstração: a integração completa fica no AI Action
      categoria: "Comercial",
      minutos: 5,
      resumo: "Uma página de vendas que se monta para cada visitante: cada seção aberta vira um sinal, e o Jev decide o que mostrar e sempre diz por quê.",
      problema: "A página de vendas é a mesma para todo mundo. O dono de PME, o CFO cético e a gestora de atendimento leem o mesmo texto, na mesma ordem, e cada um sai com a dúvida que o fez desistir.",
      quemSofre: "Quem cuida de marketing, vendas ou produto digital e vê visitantes saírem sem entender que a oferta servia para eles.",
      resultado: "O site do AI Action que reorganiza as seções, recomenda a porta certa, marca a dúvida do momento e mostra no painel o que aprendeu com cada visita.",
      processo: "Publicar no Render → abrir o site e simular um visitante → criar a conta de admin → conectar o Jev e ler o painel.",
      setup: "/setup",
      servico: "site-inteligente-ai-journey",
      criterios: [
        ["A aplicação está no ar na sua conta do Render", "Abra a URL que o Render entregou; o site do AI Action deve carregar sem erro."],
        ["O site muda com o que o visitante abre", "Use Simular visitante e confira a porta recomendada e a lente do Jev mudando."],
        ["O painel mostra o que o site aprendeu", "Crie a conta em Área do admin e abra /painel: visitas, perfis e dúvidas aparecem."],
      ],
      roteiro: [
        ["Publicar no Render", "O Render lê o Blueprint e sobe a imagem pronta na sua conta, no plano gratuito. Você não constrói nada.", "Render", 2],
        ["Abrir o site e simular um visitante", "Dono de PME, CFO cético ou gestora de atendimento: um cursor fantasma navega e o Jev reage.", "Render", 1],
        ["Criar a conta de administrador", "Em Área do admin, a conta protege a chave e libera o painel com 42 visitas de exemplo.", "Render", 1],
        ["Conectar o OpenRouter", "Em /setup, Conectar com o OpenRouter. O site passa a usar o Jev de verdade, com teto diário de gasto.", "OpenRouter", 1],
      ],
      antes: [
        "Uma conta no Render (o plano gratuito serve para esta demo)",
        "Uma conta no OpenRouter só para as decisões ao vivo; sem ela, o modo demonstração mostra tudo",
        "No plano gratuito, conta e visitas se perdem a cada nova publicação (os exemplos voltam sozinhos)",
      ],
    },
    {
      id: "venda-inteligente-ai-journey",
      nome: "Venda Inteligente",
      categoria: "Comercial",
      minutos: 5,
      resumo: "Venda o AI Action por voz para uma de três clientes interpretadas pela IA e veja o Jev ler cada resposta e recomendar a sua próxima abordagem.",
      problema: "No meio da ligação, quem vende precisa perceber quem é a cliente, qual objeção trava a compra e qual argumento usar agora. Quando percebe, a venda já esfriou.",
      quemSofre: "Quem vende por telefone, vídeo ou WhatsApp e quer treinar a abordagem certa para cada cliente, e não o mesmo roteiro para todos.",
      resultado: "Uma ligação de treino por voz com a ElevenLabs em que três clientes (fácil, média e difícil) reagem ao que você diz e o Jev decide, em milissegundos, perfil, objeção, chance de compra e a estratégia da sua próxima fala.",
      processo: "Publicar no Render → criar a conta no app → escolher a cliente e ligar → conectar o OpenRouter e a ElevenLabs para a ligação ao vivo.",
      setup: "/configuracoes",
      servico: "venda-inteligente-ai-journey",
      elevenlabs: true,
      criterios: [
        ["A aplicação está no ar na sua conta do Render", "Abra a URL que o Render entregou; a tela de criar a conta deve carregar sem erro."],
        ["Uma ligação de exemplo mostra o Jev lendo a cliente", "Toque a ligação de exemplo da Renata e confira a chance de compra e a recomendação mudando a cada resposta."],
        ["Você vende por voz para uma cliente", "Conecte o OpenRouter e a ElevenLabs em Configurações, ligue para a Marta e apresente o programa: ela responde com a voz dela e o Jev recomenda a sua próxima fala."],
      ],
      roteiro: [
        ["Publicar no Render", "O Render lê o Blueprint e sobe a imagem pronta na sua conta, no plano gratuito. Você não constrói nada.", "Render", 2],
        ["Criar a sua conta no app", "O primeiro acesso cria a conta de administrador. Ela protege as chaves que você vai conectar.", "Render", 1],
        ["Escolher a cliente e ligar", "Renata, Marta ou Juliana. Sem nenhuma chave, a cliente segue um roteiro e o Jev roda em modo demonstração.", "Render", 1],
        ["Conectar o OpenRouter e a ElevenLabs", "Em Configurações, conecte o OpenRouter em um clique e cole a chave da ElevenLabs: cada cliente ganha a própria voz.", "ElevenLabs", 1],
      ],
      antes: [
        "Uma conta no Render (o plano gratuito serve para esta demo)",
        "Uma chave da ElevenLabs com Text to Speech liberado, para a voz das clientes (sem ela, fala a voz do navegador)",
        "Chrome, Edge ou Safari com microfone; com fone de ouvido a ligação fica mais natural",
      ],
    },
  ],

  // Amostra do catálogo do AI Action (ai-action-demo/catalogo.json), exibida bloqueada.
  bloqueadas: [
    { nome: "Agente de Kanban", categoria: "Operações", minutos: 4, resumo: "Cria, move, comenta e arquiva os cartões do seu quadro Kanban a partir de comandos que você escreve em português." },
    { nome: "AutoML", categoria: "Financeiro", minutos: 5, resumo: "Lê a sua planilha de histórico, treina sozinho os modelos de previsão, escolhe o melhor e explica em português o que pesa no resultado." },
    { nome: "Atendente no WhatsApp", categoria: "Atendimento", minutos: 5, resumo: "Responde texto, áudio e fotos com o conhecimento da empresa, lembra cada cliente e avisa quando precisa de uma pessoa." },
    { nome: "Prospecção com IA", categoria: "Comercial", minutos: 4, resumo: "Pesquisa empresas e pessoas pelo perfil ideal, qualifica com evidências públicas e escreve as mensagens da abordagem." },
    { nome: "PDI do Time", categoria: "Pessoas", minutos: 3, resumo: "Cruza as entregas da pessoa com os objetivos da empresa e gera um plano de desenvolvimento de 90 dias." },
    { nome: "Posts em Minutos", categoria: "Marketing", minutos: 3, resumo: "Escreve o post para LinkedIn, Instagram e X a partir de um briefing curto e gera a imagem." },
    { nome: "Analista Financeiro", categoria: "Financeiro", minutos: 3, resumo: "Lê o CSV de despesas, mostra os números que importam e responde perguntas em linguagem natural." },
    { nome: "Voz do Cliente", categoria: "Atendimento", minutos: 3, resumo: "Agrupa comentários por tema, mede o sentimento e o NPS e prioriza o que fazer." },
    { nome: "Entrevistadora IA", categoria: "Pessoas", minutos: 5, resumo: "Entrevista o candidato por voz a partir da vaga e entrega um parecer técnico e cultural para o gestor decidir." },
    { nome: "Ata Executiva", categoria: "Operações", minutos: 3, resumo: "Transcreve o áudio da reunião e gera a ata com ações, prazos e o e-mail de follow-up." },
    { nome: "Voice SDR", categoria: "Comercial", minutos: 5, resumo: "Uma SDR por voz liga para o lead, qualifica pelo roteiro da empresa e marca a reunião na agenda do especialista." },
    { nome: "Vídeos de Campanha", categoria: "Marketing", minutos: 4, resumo: "A partir do briefing e da imagem do produto, propõe três conceitos com roteiro por cena e legendas por rede." },
  ],
};
